#! /bin/bash

#if [ -x $HOME/.local/bin/check_dual_monitor_bspwm];then
#    bash check_dual_monitor_bspwm
#fi

sxhkd &
wmname LG3D &

#Assign workspaces depending on monitor
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1' | grep -w 'connected')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1366x768 --rotate normal --left-of eDP-1
    bspc monitor eDP-1 -d I II III IV V
    bspc monitor HDMI-1 -d VI VII VIII IX X
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --off
    bspc monitor eDP-1 -d I II III IV V VI VII
fi

#Launch Polybar
if [ -x /usr/local/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh
fi


bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


feh --bg-scale ~/Pictures/minimalism-sunset.jpg
pkill picom; picom --experimental-backends &

